### ISSUE TITLE
why sumBy is deprecated?

### ISSUE THREAD

**Issue by mijaevans** [cibernox/ember-cpm#113]
Just found this addon and it's great. I'd like to add vector versions of some of the computed properties. Normally, it would be most efficient to use reducedComputed. sumBy used this method, but it was deprecated for a sum(map) combination.

Before diving in, is there a reason not to use reducedComputed? Vector functions work on the rows so adding/removing items is a good way to update calculations.

I'm a noob to git and contributing so any feedback would be appreciated.

**Comment by backspace** [comment]
Is it tacky to post in a closed issue like this? I could open a new one…

I noticed that I was getting deprecation warnings on `sumBy`, so I tried using the composed version. Originally [I had this](https://github.com/backspace/awdb/blob/primary/app/models/issue.js#L16-L18):

    persistedPrintings: Ember.computed.filterBy('printings', 'isNew', false),
    printingsCopies: sumBy('persistedPrintings', 'count'),

When I change `printingsCopies` to this:

    printingsCopies: sum(Ember.computed.mapBy('persistedPrintings', 'count')),

Now I get this error `Reduce of empty array with no initial value` for one model because `persistedPrintings` is empty. So the goal of allowing “developers to mix other macros together without defining a bunch of otherwise-useless intermediate properties” looks like it might not succeed in my case. Is there some way I can get something close to the simplicity of `sumBy`?

Thanks for this library, regardless!

**Comment by jeffreybiles** [comment]
The suggested solution is also not working for me.  The problem seems to be that the correct fields are not being watched.

`totalDocumentaryBudget: EmberCPM.Macros.sumBy('documentaries', 'budget')` works as expected, and when I change a budget the total updates.  

`totalDocumentaryBudget: EmberCPM.Macros.sum(Ember.computed.mapBy('documentaries', 'budget'))` initially calculates correctly, but then does not update when I change a budget.

The solution suggested in the `sumBy` deprecation references a method that does not exist: `Ember.deprecate("[DEPRECATED: EmberCPM/sumBy] Please use a combination of EmberCPM.Macros.sum and EmberCPM.Macros.mapBy \nEmberCPM.Macros.sum(EmberCPM.Macros.mapBy('list', 'value'))");` EmberCPM does not implement a mapBy, at least in master.

Is there something that I'm missing?
